; Cardputer = M5StampS3 (ESP32-S3FN8): 8 MB flash, ~512 KB SRAM, без PSRAM
[env:cardputer]
platform      = espressif32
board         = m5stack-stamps3   ; правильная плата (БЫЛО esp32s3box — неверно)
framework     = arduino           ; M5Cardputer/LovyanGFX = Arduino (БЫЛО espidf — не соберётся)
monitor_speed = 115200
build_flags =
    -O2                           ; оптимизация под скорость
    -I src                        ; чтобы include "components/..." работал
lib_deps =
    m5stack/M5Cardputer
